### ISSUE TITLE
gke: add initial step that checks for failing namespaces that have persisted for certain interval

### ISSUE THREAD

**Issue by murog** [GoogleCloudPlatform/cloudbuild-integration-testing#10]

**Comment by davidstanke** [comment]
Thinking about this more, I suggest instead of "let's find all the namespaces that are orphaned," we should make it specific to the build that's being run. Something like:

1. determine the namespace to be created (probably ==build_id)
2. schedule a job to delete that namespace after X hours (let's say 48)
3. create the namespace
4. run tests
*steps after this will not run if tests fail*
5. delete the namespace
6. remove the scheduled job as it's now unnecessary

To schedule the job, we can use [Kubernetes Cron Scheduling](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/).

(AFAICT, there's no kubernetes equivalent of the linux `at` command [which is designed for executing jobs exactly once], but I believe we can get close enough with cron... or maybe some other solution)

**Comment by murog** [comment]
Issue was opened while in development, closing for now while project is in maintenance mode.
